#!/bin/bash
# ZJU Quantum Compiler public smoke demo.

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
RESULTS_DIR="${PROJECT_DIR}/results/public_demo"
PYTHON="${PROJECT_DIR}/.venv/bin/python"
MODEL_PATH="${PROJECT_DIR}/models/default/npqr-default.pt"

export PYTHONPATH="${PROJECT_DIR}"
export PYTHONDONTWRITEBYTECODE=1

if [ ! -x "${PYTHON}" ]; then
    echo "[error] virtualenv Python not found: ${PYTHON}"
    exit 1
fi

mkdir -p "${RESULTS_DIR}"

echo "[1/5] qcompiler info"
"${PYTHON}" -m src.cli info | tee "${RESULTS_DIR}/01_qcompiler_info.txt"

echo "[2/5] default model"
test -f "${MODEL_PATH}"
ls -lh "${MODEL_PATH}" | tee "${RESULTS_DIR}/02_default_model.txt"

echo "[3/5] REST status smoke"
"${PYTHON}" - <<'PY' | tee "${RESULTS_DIR}/03_api_status.json"
import json
from fastapi.testclient import TestClient
from src.server.app import app

client = TestClient(app)
response = client.get("/api/status")
response.raise_for_status()
print(json.dumps(response.json(), ensure_ascii=False, indent=2))
PY

echo "[4/5] NPQR compile smoke"
"${PYTHON}" - <<'PY' | tee "${RESULTS_DIR}/04_npqr_compile.json"
import json
from fastapi.testclient import TestClient
from src.server.app import app

client = TestClient(app)
response = client.post("/api/compile", json={"example": "ghz5", "backend": "npqr", "topology": "tokyo"})
response.raise_for_status()
body = response.json()
print(json.dumps({
    "status": body["status"],
    "backend": body["backend"],
    "swaps": body["swaps"],
    "depth": body["depth"],
    "sabre_fallback": body["components"]["sabre_fallback"],
    "model_path": body["model_path"],
}, ensure_ascii=False, indent=2))
PY

echo "[5/5] SABRE baseline smoke"
"${PYTHON}" - <<'PY' | tee "${RESULTS_DIR}/05_sabre_compile.json"
import json
from fastapi.testclient import TestClient
from src.server.app import app

client = TestClient(app)
response = client.post("/api/compile", json={"example": "ghz5", "backend": "sabre", "topology": "tokyo"})
response.raise_for_status()
body = response.json()
print(json.dumps({
    "status": body["status"],
    "backend": body["backend"],
    "heuristic": body["heuristic"],
    "swaps": body["swaps"],
    "depth": body["depth"],
}, ensure_ascii=False, indent=2))
PY

cat > "${RESULTS_DIR}/README.md" <<'EOF'
# Public demo output

This directory is generated by `bash run_public_demo.sh`.

- NPQR is the default route.
- SABRE is the comparison baseline.
- The default model is `models/default/npqr-default.pt`.
- Generated files are local smoke outputs and are not committed.
EOF

echo "Demo output written to ${RESULTS_DIR}"
